-- =============================================================================
-- BigBirdBot — PostgreSQL schema (translated from the SQL Server schema that
-- Data/BigBirdContext.cs maps against). Written by hand from that context's
-- OnModelCreating, column for column — there are no EF Core migrations on
-- either database engine, so this is the single source of truth for the
-- Postgres side, the same role SQL/Database/dbo/*.sql plays for SQL Server.
--
-- Scope: only the 23 tables the application actually uses today (every
-- DbSet in BigBirdContext). Everything from the stripped features
-- (economy/pets/games/shop/stock/forge/etc.) stays SQL-Server-only —
-- archival data that predates this migration, not something the bot reads
-- or writes, so there's nothing to recreate here.
--
-- Type translation notes:
--   bit            -> boolean
--   datetime(2)    -> timestamp                 (no app code is timezone-aware;
--                                                 every DateTime here is naive,
--                                                 matching SQL Server's datetime)
--   int IDENTITY   -> integer GENERATED BY DEFAULT AS IDENTITY
--   nvarchar(n)    -> varchar(n)
--   nvarchar(max)  -> text
--   Every identifier is double-quoted to preserve the exact PascalCase
--   BigBirdContext expects — Postgres folds unquoted identifiers to
--   lowercase, which would break every HasColumnName("...") mapping.
--
-- No DEFAULT constraints are added: BigBirdContext's services set every
-- column explicitly in C# before insert (see its class doc comment) rather
-- than relying on database-side defaults, so there's nothing here for a
-- default to do.
--
-- No foreign keys: the only one in the entire SQL Server schema
-- (FK_PetJournal_Pet) belonged to a table dropped in the pet-system strip,
-- so table creation order below doesn't matter.
--
-- Run once against a fresh `discordbot` database:
--   psql -U discordbot -d discordbot -h localhost -f 001_InitialSchema.sql
-- =============================================================================

-- ── Keywords ─────────────────────────────────────────────────────────────

CREATE TABLE "ChatKeyword"
(
    "ID"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ChatKeyword" varchar(50)  NOT NULL,
    "FilePath"  text         NOT NULL,
    "CreatedOn" timestamp    NOT NULL,
    "NSFW"      boolean      NOT NULL
);

CREATE TABLE "ChatKeywordMap"
(
    "ID"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AddKeyword" varchar(50) NOT NULL,
    "ServerID"   bigint      NOT NULL,
    "CreatedOn"  timestamp   NOT NULL,
    "CreatedBy"  varchar(50) NULL,
    -- Faithful to the SQL Server computed column: replaces every "add"
    -- substring, not just the leading prefix.
    "Keyword"    varchar(50) GENERATED ALWAYS AS (replace("AddKeyword", 'add', '')) STORED
);

CREATE TABLE "ChatKeywordAlias"
(
    "ID"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Alias"     varchar(50) NOT NULL,
    "Keyword"   varchar(50) NOT NULL,
    "ServerID"  bigint      NOT NULL,
    "CreatedOn" timestamp   NOT NULL,
    "CreatedBy" varchar(50) NOT NULL
);

CREATE TABLE "UsersScheduledKeyword"
(
    "UserID"           varchar(50)  NOT NULL,
    "ChatKeyword"       varchar(100) NOT NULL,
    "ScheduledDateTime" timestamp    NOT NULL,
    PRIMARY KEY ("UserID", "ChatKeyword", "ScheduledDateTime")
);

-- ── Users / Servers ──────────────────────────────────────────────────────

CREATE TABLE "Users"
(
    "UserID"    varchar(50)  NOT NULL,
    "Username"  varchar(200) NOT NULL,
    "JoinDate"  timestamp    NOT NULL,
    "ServerUID" bigint       NOT NULL,
    "Nickname"  varchar(200) NULL,
    "PronounID" integer      NULL,
    "CreatedOn" timestamp    NOT NULL,
    "DeletedOn" timestamp    NULL,
    "LastSeen"  timestamp    NULL,
    PRIMARY KEY ("UserID", "ServerUID")
);

CREATE TABLE "Servers"
(
    "ServerID"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ServerUID"            bigint       NOT NULL,
    "ServerName"           varchar(200) NOT NULL,
    "DefaultChannelID"     bigint       NULL,
    "Volume"               integer      NOT NULL,
    "FixEmbed"             boolean      NOT NULL,
    "IsPlayerConnected"    boolean      NOT NULL,
    "IsActive"             boolean      NOT NULL,
    "CreatedOn"            timestamp    NOT NULL,
    "AnnouncementsEnabled" boolean      NOT NULL
);

CREATE TABLE "Pronouns"
(
    "ID"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Pronoun" varchar(100) NOT NULL
);

-- ── Audit ────────────────────────────────────────────────────────────────

CREATE TABLE "AuditLog"
(
    "AuditLogID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Command"    varchar(50) NOT NULL,
    "ServerUID"  bigint      NOT NULL,
    "CreatedOn"  timestamp   NOT NULL,
    "CreatedBy"  varchar(50) NOT NULL
);

CREATE TABLE "AuditButtonExecuted"
(
    "ID"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ButtonID"   varchar(100) NOT NULL,
    "UserUID"    bigint       NOT NULL,
    "ServerUID"  bigint       NOT NULL,
    "ExecutedOn" timestamp    NOT NULL
);

CREATE TABLE "AuditGuildJoined"
(
    "ID"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ServerUID"  bigint       NOT NULL,
    "ServerName" varchar(100) NOT NULL,
    "JoinedOn"   timestamp    NOT NULL
);

CREATE TABLE "AuditReactionAdded"
(
    "ID"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Emoji"      varchar(50) NOT NULL,
    "MessageUID" bigint      NOT NULL,
    "UserUID"    bigint      NOT NULL,
    "ChannelUID" bigint      NOT NULL,
    "AddedOn"    timestamp   NOT NULL
);

CREATE TABLE "AuditUserJoined"
(
    "ID"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserUID"   bigint    NOT NULL,
    "ServerUID" bigint    NOT NULL,
    "JoinedOn"  timestamp NOT NULL
);

CREATE TABLE "AuditUserLeft"
(
    "ID"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserUID"   bigint    NOT NULL,
    "ServerUID" bigint    NOT NULL,
    "LeftOn"    timestamp NOT NULL
);

CREATE TABLE "AuditGameTrigger"
(
    "ID"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Game"        varchar(50) NOT NULL,
    "UserUID"     bigint      NOT NULL,
    "ServerUID"   bigint      NOT NULL,
    "TriggeredOn" timestamp   NOT NULL
);

-- ── AutoRole ─────────────────────────────────────────────────────────────

CREATE TABLE "GuildAutoRole"
(
    "GuildId"   bigint    NOT NULL PRIMARY KEY,
    "RoleId"    bigint    NOT NULL,
    "UpdatedAt" timestamp NOT NULL
);

-- ── Scheduling (reminders / birthdays) ──────────────────────────────────

CREATE TABLE "Reminders"
(
    "ReminderID"  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID"      varchar(50)   NOT NULL,
    "Message"     varchar(1000) NOT NULL,
    "RemindAtUtc" timestamp     NOT NULL,
    "Sent"        boolean       NOT NULL
);

CREATE TABLE "Birthday"
(
    "BirthdayID"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BirthdayDate"    timestamp    NOT NULL,
    "BirthdayUser"    varchar(200) NOT NULL,
    "BirthdayGuild"   varchar(200) NOT NULL,
    "Sent"            boolean      NOT NULL,
    "BirthdayChannel" varchar(200) NULL
);

-- ── AI chat history ──────────────────────────────────────────────────────

CREATE TABLE "BotAIMessage"
(
    "BotAIMessageID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID"         varchar(50) NOT NULL,
    "ServerUID"      varchar(50) NOT NULL,
    "ChatRole"       varchar(10) NOT NULL,
    "ChatMessage"    text        NOT NULL,
    "CreatedOn"      timestamp   NOT NULL,
    "ChannelID"      varchar(50) NULL
);

-- ── Bonus word puzzle ────────────────────────────────────────────────────

CREATE TABLE "PetWordPuzzle"
(
    "PuzzleID"  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ChannelID" varchar(50)  NOT NULL,
    "Word"      varchar(100) NOT NULL,
    "ExpiresAt" timestamp    NOT NULL,
    "Claimed"   boolean      NOT NULL
);

CREATE TABLE "Words"
(
    "ID"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Word" varchar(10) NOT NULL
);

-- ── Music / audio ────────────────────────────────────────────────────────

CREATE TABLE "Music"
(
    "MusicID"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ServerUID" bigint       NOT NULL,
    "VideoID"   varchar(200) NOT NULL,
    "Author"    varchar(200) NOT NULL,
    "Title"     varchar(400) NOT NULL,
    "URL"       varchar(1000) NOT NULL,
    "CreatedOn" timestamp    NOT NULL,
    "CreatedBy" varchar(50)  NOT NULL
);

CREATE TABLE "MusicQueue"
(
    "MusicQueueID"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MusicID"        integer      NOT NULL,
    "ServerUID"      bigint       NOT NULL,
    "VoiceChannelID" bigint       NOT NULL,
    "TextChannelID"  bigint       NOT NULL,
    "URL"            varchar(1000) NOT NULL,
    "CreatedOn"      timestamp    NOT NULL,
    "CreatedBy"      varchar(50)  NOT NULL
);

CREATE TABLE "PlayerConnected"
(
    "PlayerID"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ServerUID"      bigint      NOT NULL,
    "VoiceChannelID" bigint      NOT NULL,
    "TextChannelID"  bigint      NOT NULL,
    "CreatedOn"      timestamp   NOT NULL,
    "CreatedBy"      varchar(50) NOT NULL
);
